### ISSUE TITLE
The server is returning 500 error for image

### ISSUE THREAD

**Issue by PeterDaveHello** [retrohacker/dockeri.co#16] opened 2022-09-01 08:41 UTC
Hi @retrohacker, there seems to be an issue with image generation, not sure what's wrong, didn't have any details of that error.

Result of https://dockeri.co/image/peterdavehello/azcopy:

![image](https://user-images.githubusercontent.com/3691490/187871143-46aca46d-f295-424a-8861-ebc3f0c91197.png)

Thanks for the service!

**Comment by robertsLando** [comment] 2022-09-27 07:15
Having same error

**Comment by robertsLando** [comment] 2022-10-10 14:31
@retrohacker any clue?

**Comment by robertsLando** [comment] 2022-10-11 14:35
It's a pity, this was the best docker badge out there....

**Comment by robertsLando** [comment] 2022-10-11 15:42
The error seems related to comments call made in [badge.js](https://github.com/retrohacker/dockeri.co/blob/master/src/views/badge.js#L38), it returns 404.

@PeterDaveHello I have created my personal project starting from this, it is on a free server so requests are limited so reach me via PM so I can send the link to you

**Comment by PeterDaveHello** [comment] 2022-10-11 17:57
> It's a pity, this was the best docker badge out there....

Yes, as https://github.com/microscaling/microbadger it's archived

> @PeterDaveHello I have created my personal project starting from this, it is on a free server so requests are limited so reach me via PM so I can send the link to you

Thanks for your kindness, but I use it at many public repos, the url could be leaked soon, plus there're so many need to be updated, and there's no rush, let's wait and see if any miracle can happen before the end of the year ;)

**Comment by robertsLando** [comment] 2022-10-11 18:59
You could fork my project and setup your own server for free in 10 seconds, I used Cyclic free plan.

**Comment by PeterDaveHello** [comment] 2022-10-11 20:29
> You could fork my project and setup your own server for free in 10 seconds, I used Cyclic free plan.

Is it a public fork? Would like to take a look 👍

**Comment by robertsLando** [comment] 2022-10-12 06:13
@PeterDaveHello check this: https://github.com/robertsLando/starter-express-api

Just click on the button on readme, create a free account (with github) and select my fork as template project. It will start a server in few seconds :)

**Comment by PeterDaveHello** [comment] 2022-10-14 06:01
> BTW, I tried to send direct message on Twitter to reach out two weeks ago, but no response yet 😅

Just got a reply, the issue is now noticed, let's see if we have any luck to get it back soon 🎉

**Comment by retrohacker** [comment] 2022-11-17 21:38
Heya folks - have been busy with a lot lately and dockeri.co isn't currently a top priority for me right now.

I suspect the issue is an EOL labmda - but not sure. The code itself is pretty straightforward. If I did this again I'd probably convert it to a cloudflare function. If anyone wants to take a pass at that work, I can commit to updating dockeri.co with that cloudflare function.

I guess I'm saying PRs welcome for restoring the service :-)

1. Migrate to a cloudflare worker
2. Submit PR doing the migration
3. I'll do the work on my end to get this back up on cloudflare

**Comment by retrohacker** [comment] 2022-11-17 21:40
> It's a pity, this was the best docker badge out there....

Thanks, credit where credit is due - this was a wholesale copy of Rod Vagg's npm badge, I just wired it up to docker instead.

**Comment by robertsLando** [comment] 2022-11-21 09:04
@retrohacker the problem is due to comments fetch, that api always return error as seems it doesn't exists anymore, see https://github.com/retrohacker/dockeri.co/blob/master/src/views/badge.js#L38

I have just removed the comment fetch part and always works

**Comment by retrohacker** [comment] 2022-11-29 21:16
Got it, thanks!

Have some downtime in late December between contracts. I might try the cloudflare migration myself then.

**Comment by robertsLando** [comment] 2022-11-30 07:21
Keep us updated and thanks for that! In the meanwhile I'm using my own hosted with [cyclic](https://cyclic.us.auth0.com/u/login?state=hKFo2SBTVUcySUtiZU15YnBaYk0wSkpwVG5LWDViZ3YzNnAyV6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIDA4TGNmYnJuVFFWenlJQkFWNmwtb1FNRGJfcjJmdHZ0o2NpZNkgb1JqTndtN3pqVHB3MjcwWXJQdk5RSHdpZm53RnlDTXo) and looks good so far

**Comment by retrohacker** [comment] 2022-12-20 19:09
Hey @robertsLando and @PeterDaveHello, thanks for all of your help on this (and for pinging me!)

I migrated the service today. Should be up and running at dockerico.blankenship.io immediately. I'm in the process of migrating DNS for dockeri.co, once DNS switches over dockeri.co should start working again (though I'm planning on redirecting to dockerico.blankenship.io soon)!

**Comment by PeterDaveHello** [comment] 2022-12-20 19:27
That's very awesome, thank you very much for the effort!

**Comment by robertsLando** [comment] 2022-12-21 09:51
Thanks @retrohacker

**Comment by PeterDaveHello** [comment] 2023-02-04 15:08
Now we can see that requests will be 302 redirected to dockerico.blankenship.io, from dockeri.co, just GitHub doesn't seem to load/render the image properly, at least I can't make it loaded here: https://github.com/PeterDaveHello/tor-socks-proxy

**Comment by retrohacker** [comment] 2023-02-04 17:29
Oh bummer - I’ll look into this this week. Thought 302 would be fine for images.

**Comment by retrohacker** [comment] 2023-02-07 16:40
I believe this was fixed in https://github.com/retrohacker/dockeri.co/commit/052e2fa1a5a48dca0205f8ea916d3537e3a8fc6d

Looking at your repo I see the badge now.

**Comment by PeterDaveHello** [comment] 2023-02-07 17:01
That's pretty sweat! Thanks again @retrohacker 🎉 

If there's no other related issues around, I believe that we can make the case closed 👍

**Comment by retrohacker** [comment] 2023-02-10 03:33
Thanks for reporting back Peter.

Just wanted to add an extra note of gratitude. Thanks for bringing this to my attention - it wouldn't have been fixed for a long while without you :heart: 

You also saved me a lot of $$$ - the 5xx errors were causing my CloudWatch bill to inflate, and I hadn't been checking my AWS invoices. You literally saved me $100s of dollars in hosting costs - I owe you a :coffee: or :beer: at some point.

**Closed by retrohacker** 2023-02-10 03:33 UTC

**Comment by PeterDaveHello** [comment] 2023-02-10 09:04
@retrohacker you're too kind, we're the one should thank you providing such a great free service (maybe also an open source project? just not sure because no license information yet), thank you again!

**Comment by retrohacker** [comment] 2023-02-10 15:26
Added in 3d10ce89763636c733071943c3a23699bbdfd60d

Thanks for noting the omission
